name: debounce_throttle
description: A debouncer and throttle that works with Futures, Streams, and callbacks.
version: 2.0.0
homepage: https://github.com/jifalops/debounce_throttle

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.0.0
  simple_observable: ^2.0.0

dev_dependencies:
  test: ^1.0.0
